name: Create and publish a Docker image

on:
  push:
    branches: ['main']
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    name: Build and Push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          EVENT_NAME=${{ github.event_name }}
          IS_FORK=${{ github.event.pull_request.head.repo.fork }}

          echo "Event Name = $EVENT_NAME"
          echo "Is Fork = $IS_FORK"
          
          if [ "$EVENT_NAME" = "push" ]; then
            echo "::set-output name=should_push::true"
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            if [ "$IS_FORK" = "true" ]; then
              echo "::set-output name=should_push::false"
            else
              echo "::set-output name=should_push::true"
            fi
          fi

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9
        with:
          cosign-release: 'v1.4.0'

      - name: Log in to the Container registry
        if: ${{ steps.prep.outputs.should_push == 'true' }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        id: build-and-push
        with:
          context: .
          push: ${{ steps.prep.outputs.should_push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}      
