name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: make build
      
    - name: Test
      run: make test
      
    - name: Run check
      run: make check
      
    - name: Run in
      run: make in
